title: Ian's CSP Blog
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: iwu78
baseurl: "/csp-blog"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
theme: jekyll-theme-leaf
plugins:
- jekyll-remote-theme
future: true
